export let weekDataObj = {
  Monday: {
    value: "Monday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Tuesday: {
    value: "Tuesday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Wednesday: {
    value: "Wednesday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Thursday: {
    value: "Thursday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Friday: {
    value: "Friday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Saturday: {
    value: "Saturday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
  Sunday: {
    value: "Sunday",
    available: false,
    startTime: "",
    endTime: "",
    timeStartValue: "--:--",
    timeEndValue: "--:--",
    otherTimes: [],
  },
};
